version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      MONGODB_URI: "mongodb://mongo:27017"
      PG_HOST: "postgres"
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      - postgres
      - mongo
      - redis

volumes:
  pg_data:
  mongo_data:
  redis_data: